export const DEFAULT_COMMAND_TIMEOUT_MS = 30_000;
export const DEFAULT_OUTPUT_CAPTURE_BYTES = 256 * 1024;

export const DEFAULT_ALLOWED_ENVIRONMENT_VARIABLES = [
	'CI',
	'FORCE_COLOR',
	'LANG',
	'LC_ALL',
	'NODE_ENV',
	'NO_COLOR',
	'PATH',
	'TERM',
	'TMPDIR'
];
