// Serializable contracts and Zod schemas shared across UI, API routes, Workflows, and Activities.
// Must not import SDK clients, DB client, or UI libraries.

export type SubmitTurnInput = {
	message: string;
	/** When true, the run will fan out research, code, and critic child workflows. */
	delegateSubagents?: boolean;
	/** Model ID to use for this turn. Defaults to the workflow's DEFAULT_MODEL when omitted. */
	model?: string;
	/**
	 * Max total estimated cost in USD for this run. When > 0, overrides `maxEstimatedCostUsd`
	 * in the default budget. When 0 or omitted, the workflow's DEFAULT_RUN_BUDGET applies.
	 * Note: 0 does NOT disable the budget — it falls back to the default $1 cap.
	 */
	maxBudgetUsd?: number;
};

export type SubmitTurnResult = {
	accepted: boolean;
	runId: string;
};

export type SessionState = {
	sessionKey: string;
	status: 'active' | 'idle' | 'finalizing' | 'complete';
	activeRunId: string | null;
	queueDepth: number;
	completedRunCount: number;
};

/** Hard limits enforced by AgentRunWorkflow at runtime. */
export type RunBudget = {
	/** Max number of model round-trips per run. */
	maxModelCalls: number;
	/** Max number of tool calls per run. */
	maxToolCalls: number;
	/** Max number of child workflow launches per run. */
	maxChildWorkflows: number;
	/** Max total tokens (input + output) across all model calls. */
	maxTokens: number;
	/** Max total actions (tool calls + child workflows) per run. */
	maxActions: number;
	/** Max wall-clock milliseconds from run start to completion. */
	maxActiveWallClockMs: number;
	/** Max total estimated cost in USD across all model calls. */
	maxEstimatedCostUsd: number;
};

export type AgentRunInput = {
	sessionKey: string;
	runId: string;
	message: string;
	/** Model ID to use for the run. Defaults to the project default in the workflow. */
	model?: string;
	/** Optional system prompt override for the run. */
	systemPrompt?: string;
	/** Tool schemas to expose to the model. */
	tools?: ModelToolSchema[];
	workspacePath?: string;
	approvalTtlMs?: number;
	delegateSubagents?: boolean;
	/** Runtime budget caps. Workflow uses DEFAULT_RUN_BUDGET when omitted. */
	budget?: RunBudget;
};

export type AgentRunResult = {
	runId: string;
	status: 'complete' | 'failed' | 'cancelled';
	finalAnswer: string;
	budgetLedger?: BudgetLedgerSnapshot;
	timelineLanes?: RunTimelineLane[];
	criticAnnotations?: CriticAnnotation[];
	/**
	 * Memory candidate refs generated by this run. The session workflow
	 * accumulates these across runs and surfaces them via getMemorySnapshot.
	 */
	memoryRefs?: string[];
	/**
	 * Errors encountered while writing memory candidates for this run.
	 * Non-empty when one or more `writeMemoryCandidate` activity calls failed.
	 * Failures are surfaced here rather than swallowed so callers can observe
	 * and act on them.
	 */
	memoryWriteErrors?: string[];
};

/** Input for the submitSteering session Update. */
export type SubmitSteeringInput = {
	/** Steering message to inject into the active run at the next model boundary. */
	message: string;
};

/** Result of the submitSteering session Update. */
export type SubmitSteeringResult = {
	accepted: boolean;
	/** Present when accepted is false, explaining why the steering was rejected. */
	reason?: string;
};

/** Input for the interruptRun session Update. */
export type InterruptRunInput = {
	/** Optional replacement message to queue as the next run after interruption. */
	replacement?: string;
};

/** Result of the interruptRun session Update. */
export type InterruptRunResult = {
	interrupted: boolean;
	/** runId of the replacement turn, if one was queued. */
	replacementRunId?: string;
};

/** Snapshot of memory refs accumulated by the session across all completed runs. */
export type SessionMemorySnapshot = {
	memoryRefs: string[];
};

/** Snapshot of sandbox / workspace state tracked by the session. */
export type SessionSandboxSnapshot = {
	sessionKey: string;
	/** Absolute path to the sandbox workspace, or null if none has been provisioned. */
	workspacePath: string | null;
};

export type BudgetLedgerEntry = {
	workflowId: string;
	laneId: string;
	label: string;
	usage: ModelUsage;
};

export type BudgetLedgerSnapshot = {
	limit: ModelUsage;
	used: ModelUsage;
	remaining: ModelUsage;
	entries: BudgetLedgerEntry[];
};

export type CriticAnnotation = {
	id: string;
	laneId: string;
	message: string;
	blocking: false;
};

export type RunTimelineLane = {
	id: string;
	label: string;
	kind: 'parent' | 'subagent';
	status: 'running' | 'complete' | 'failed' | 'cancelled';
	budget?: ModelUsage;
	children?: RunTimelineLane[];
	annotations?: CriticAnnotation[];
};

export type SubagentKind = 'research' | 'code' | 'critic';

export type SubagentWorkflowInput = {
	parentRunId: string;
	subagentRunId: string;
	sessionKey: string;
	kind: SubagentKind;
	message: string;
	finalAnswer?: string;
	budgetDebit: BudgetLedgerEntry;
	/** Model ID to use for the subagent's model call. */
	model?: string;
};

export type SubagentWorkflowResult = {
	parentRunId: string;
	subagentRunId: string;
	kind: SubagentKind;
	status: 'complete' | 'failed' | 'cancelled';
	finalAnswer: string;
	budgetDebit: BudgetLedgerEntry;
	timelineLane: RunTimelineLane;
	annotations?: CriticAnnotation[];
};

export type ScheduledAgentInput = {
	scheduleId: string;
	prompt: string;
};

export type CreateScheduleInput = {
	name: string;
	description?: string;
	cronExpression: string;
	prompt: string;
};

export type ScheduleProjection = {
	id: string;
	temporalScheduleId: string;
	targetSessionKey: string;
	name: string;
	description: string | null;
	cronExpression: string;
	prompt: string;
	status: 'active' | 'paused' | 'deleted';
	lastRunAt: string | null;
	nextRunAt: string | null;
	createdAt: string;
	updatedAt: string;
};

export type TriggerScheduleResult = {
	schedule: ScheduleProjection;
	targetSessionKey: string;
};

export type DeleteScheduleResult = {
	scheduleId: string;
	deleted: true;
};

export type ModelUsage = {
	inputTokens: number;
	outputTokens: number;
	estimatedCostUsd: number;
};

export type ModelToolSchema = {
	identity: {
		name: string;
		namespace?: string;
		version?: string;
	};
	display: {
		description: string;
		title?: string;
	};
	input: Record<string, unknown>;
};

/**
 * A confirmed memory note carried into the model context.
 * Serialisable subset of `MemoryNote` — includes the fields needed for
 * provenance display in the assembled system prompt.
 */
export type ContextMemoryNote = {
	id: string;
	/** Memory layer: session_summary, durable, or action-sensitive. */
	layer: string;
	content: string;
	tags: string[];
};

export type ModelCallInput = {
	sessionId: string;
	runId: string;
	/** Deterministic per-workflow model call identifier used for idempotent side effects. */
	modelCallId: string;
	model: string;
	tools?: ModelToolSchema[];
	maxTokens?: number;
	systemPrompt?: string;
	/**
	 * Steering messages buffered by the session and forwarded to the run.
	 * Injected as additional user context before this model call.
	 * Drained from the run's steering buffer at each model boundary.
	 */
	steeringMessages?: string[];
	/**
	 * Confirmed memory notes retrieved by the workflow before this model call.
	 * Assembled from the FTS5+sqlite-vec RRF retrieval path and included in
	 * the system prompt with full provenance (id, layer, tags, content).
	 */
	memoryNotes?: ContextMemoryNote[];
	/**
	 * Absolute path to the session workspace, when a sandbox has been
	 * provisioned. Included as a workspace-reference line in the system prompt
	 * so the model knows which directory to target for file operations.
	 */
	workspacePath?: string;
};

export type NormalizedToolCall = {
	id: string;
	name: string;
	input: unknown;
};

export type NormalizedModelMessage = {
	text: string;
	toolCalls: NormalizedToolCall[];
};

export type ModelCallResult = {
	runId: string;
	model: string;
	message: NormalizedModelMessage;
	usage: ModelUsage;
};

export type ToolRiskLevel = 'low' | 'medium' | 'high';

/**
 * Describes how an idempotency key should be used when retrying this tool:
 * - `'safe'`: Tool is read-only; replaying without a key is safe.
 * - `'key-required'`: Tool has side effects that must be deduplicated; an idempotency key is required for safe retry.
 * - `'unsafe'`: Tool has state-dependent side effects that cannot be safely deduplicated even with a key.
 */
export type IdempotencyBehavior = 'safe' | 'key-required' | 'unsafe';

export type ToolMetadata = {
	risk: ToolRiskLevel;
	requiresApproval: boolean;
	taskQueue: string;
	timeoutMs: number;
	retry: {
		maximumAttempts: number;
	};
	/** Describes how this tool interacts with Temporal's idempotency ledger on retry. */
	idempotencyBehavior: IdempotencyBehavior;
};

export type ToolManifestEntry = {
	name: string;
	description: string;
	inputSchema: Record<string, unknown>;
	metadata: ToolMetadata;
};

export type ToolCallInput = {
	id: string;
	name: string;
	arguments: unknown;
	idempotencyKey?: string;
};

export type ToolPolicyDecision =
	| { status: 'allowed'; tool: ToolManifestEntry }
	| { status: 'approval_required'; tool: ToolManifestEntry; policyVersion: string }
	| { status: 'denied'; reason: string };

export type ToolExecutionInput = {
	call: ToolCallInput;
	sessionId?: string;
	/** Session key (UUIDv7) used to construct artifact object keys. */
	sessionKey?: string;
	runId?: string;
	workspacePath?: string;
};

export type ToolExecutionResult = {
	callId: string;
	toolName: string;
	outcome: 'success' | 'error' | 'approval_required' | 'denied';
	content: unknown;
	metadata?: {
		truncated?: boolean;
		originalCharacters?: number;
		idempotencyKey?: string;
		idempotencyReplayed?: boolean;
		/** Artifact ID when output was spilled to a local artifact (above TOOL_RESULT_INLINE_LIMIT). */
		spilledArtifactId?: string;
		/** Byte size of the spilled artifact content. */
		spilledBytes?: number;
	};
};

export type ApprovalTerminalState = 'approved' | 'denied' | 'remembered' | 'cancelled' | 'expired';

export type ApprovalAction =
	| 'approve'
	| 'approve_with_edits'
	| 'deny'
	| 'remember'
	| 'cancel'
	| 'expire';

export type ApprovalRequest = {
	approvalId: string;
	sessionId: string;
	runId: string;
	toolCall: ToolCallInput;
	tool: ToolManifestEntry;
	policyVersion: string;
	proposedArguments: unknown;
	argsHash: string;
	expiresAt: string;
	createdAt: string;
	/** Unified diff of changes the tool proposes to make. */
	diff?: string;
	/** Working directory in which the tool will execute. */
	workingDirectory?: string;
	/** Names (not values) of environment variables the tool will read. */
	environmentVariableNames?: string[];
	/** Snapshot identifiers the tool references or will modify. */
	snapshotReferences?: string[];
};

export type ApprovalResolutionInput = {
	approvalId: string;
	action: Exclude<ApprovalAction, 'expire'>;
	editedArguments?: unknown;
	reason?: string;
	remember?: boolean;
	actor?: 'user';
};

export type ApprovalResolution = {
	approvalId: string;
	action: ApprovalAction;
	terminalState: ApprovalTerminalState;
	canonicalArguments: unknown;
	proposedArguments: unknown;
	editedArguments?: unknown;
	reason?: string;
	remember: boolean;
	actor: 'system' | 'user';
	resolvedAt: string;
};

export type ApprovalCardState = ApprovalRequest & {
	status: 'pending' | ApprovalTerminalState;
	resolution?: ApprovalResolution;
};

export type RecordApprovalRequestInput = Omit<ApprovalRequest, 'argsHash' | 'createdAt'> & {
	createdAt?: string;
};

export type RecordApprovalResolutionInput = {
	approvalId: string;
	action: ApprovalAction;
	editedArguments?: unknown;
	reason?: string;
	remember?: boolean;
	actor: 'system' | 'user';
	resolvedAt?: string;
};

export type CompactMemoryInput = {
	sessionId: string;
	fromTranscriptCursor: number;
	reason: 'threshold' | 'manual';
};

export type LoadedMemoryCompactionInput = {
	sessionId: string;
	fromTranscriptCursor: number;
	toTranscriptCursor: number;
	transcript: string[];
	existingMemoryRefs: string[];
};

export type MemoryCompactionCandidate = {
	layer: 'session' | 'durable' | 'action_sensitive';
	content: string;
	tags?: string[];
	reason?: string | null;
};

export type MemoryCompactionSummary = {
	summary: string;
	candidates: MemoryCompactionCandidate[];
};

export type PersistMemoryCompactionInput = LoadedMemoryCompactionInput & MemoryCompactionSummary;

export type CompactMemoryResult = {
	sessionId: string;
	summaryNoteId: string;
	candidateIds: string[];
	memoryRefs: string[];
	transcriptCursor: number;
};

export type MemoryCompactionActivities = {
	loadMemoryCompactionInput(input: CompactMemoryInput): Promise<LoadedMemoryCompactionInput>;
	summarizeMemoryCompaction(input: LoadedMemoryCompactionInput): Promise<MemoryCompactionSummary>;
	persistMemoryCompaction(input: PersistMemoryCompactionInput): Promise<CompactMemoryResult>;
};

// Task queue name constants — kept here (not in src/lib/server) so Workflow code can import them.
export const TASK_QUEUE_ORCHESTRATOR = 'agent-orchestrator';
export const TASK_QUEUE_MODEL = 'model-calls';
export const TASK_QUEUE_TOOLS = 'tools-general';
export const TASK_QUEUE_SANDBOX = 'tools-sandbox';
export const TASK_QUEUE_MEMORY = 'memory';
